// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqlofsdscguzwgsacfci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxbG9mc2RzY2d1endnc2FjZmNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODM1NzEsImV4cCI6MjA2MjQ1OTU3MX0.RZYJIFt4SCVTEPu1d1SwkGrs7h-e4RlsrAF8A8pXzbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);